version: '3'
services:
  postgres:
    image: postgres
    volumes: 
      - postgresql_database:/var/lib/postgresql/data
  web1:
    build: .
    container_name: web1
    ports:
      - "8000:8000"
    volumes:
       - ".:/app"
    environment:
      - "DATABASE_URL=postgresql://postgres@postgres:5432/postgres"
    depends_on: 
      - postgres
  web2:
    build: .
    container_name: web2
    ports:
      - "8001:8000"
    volumes:
       - ".:/app"
    environment:
      - "DATABASE_URL=postgresql://postgres@postgres:5432/postgres"
    depends_on:
      - postgres
volumes: 
  postgresql_database:
